defmodule BSV.Tokens.Stas3.ConformanceTest do
  @moduledoc """
  Cross-SDK conformance: validate this Elixir implementation against the STAS 3.0
  v0.2.4 §15 golden vectors generated by the Rust SDK
  (`crates/bsv-tokens/tests/vectors/stas3_section15.json`). A byte-for-byte match
  proves the two SDKs agree on flags decoding, engine selection, locking-script
  construction, and the directive-append covenant.
  """
  use ExUnit.Case, async: true

  alias BSV.Script
  alias BSV.Tokens.ScriptFlags
  alias BSV.Tokens.Script.Stas3Builder
  alias BSV.Tokens.Factory.Stas3

  @vectors_path Path.expand("../../../support/vectors/stas3_section15.json", __DIR__)

  setup_all do
    {:ok, vectors: Jason.decode!(File.read!(@vectors_path))}
  end

  defp to_hex(bin), do: Base.encode16(bin, case: :lower)
  defp unhex(str), do: Base.decode16!(str, case: :lower)
  defp flags_byte("0x" <> hex), do: String.to_integer(hex, 16)
  defp engine_name(:v0_0_9), do: "0.0.9"
  defp engine_name(:v0_0_11), do: "0.0.11"
  # "0.0.11" -> :v0_0_11
  defp engine_atom(str), do: String.to_existing_atom("v" <> String.replace(str, ".", "_"))

  test "flags decode + engine selection match the golden vectors", %{vectors: v} do
    for f <- v["flags"] do
      {:ok, flags} = ScriptFlags.decode(<<flags_byte(f["byte"])>>)
      assert flags.freezable == f["freezable"]
      assert flags.confiscatable == f["confiscatable"]
      assert flags.nft == f["nft"]
      assert flags.augmentable == f["augmentable"]
      assert engine_name(ScriptFlags.engine(flags)) == f["engine"]
    end
  end

  test "locking-script construction is byte-identical to the golden vectors", %{vectors: v} do
    owner = unhex(v["owner_pkh"])
    redemption = unhex(v["redemption_pkh"])

    for c <- v["locking_scripts"] do
      {:ok, flags} = ScriptFlags.decode(<<flags_byte(c["flags_byte"])>>)

      action =
        case c["action"] do
          nil -> nil
          %{"type" => "augment", "data" => data} -> {:augment, unhex(data)}
        end

      {:ok, script} =
        Stas3Builder.build_stas3_locking_script_with_engine(
          owner,
          redemption,
          action,
          false,
          flags,
          engine_atom(c["engine"]),
          [],
          []
        )

      assert to_hex(Script.to_binary(script)) == c["script_hex"],
             "locking-script mismatch for vector #{c["name"]}"
    end
  end

  test "directive-append vectors are consistent and verified", %{vectors: v} do
    for d <- v["directive_append"] do
      # The covenant is a raw-byte append: expected == base ++ directive_data.
      assert d["expected_output_hex"] == d["base_output_hex"] <> d["directive_data_hex"]

      input = unhex(d["input_hex"])
      expected = unhex(d["expected_output_hex"])
      base = unhex(d["base_output_hex"])

      assert Stas3.verify_augment_directive_appended(input, expected) == :ok

      assert Stas3.verify_augment_directive_appended(input, base) ==
               {:error, :directive_not_appended}
    end
  end
end
